---
language: perl
perl:
  - "blead-thr"
  - "blead"
  - "dev-thr"
  - "dev"
  - "5.26-thr"
  # - "5.26" expclicitly with coverage in 'matrix'
  - "5.24-thr"
  - "5.24"
  - "5.22-thr"
  - "5.22"
  - "5.20-thr"
  - "5.20"
  - "5.18-thr"
  - "5.18"
  - "5.16-thr"
  - "5.16"
  - "5.14-thr"
  # - "5.14" expclicitly with coverage in 'matrix'
  - "5.12-thr"
  - "5.12"
  - "5.10-thr"
  - "5.10"
  - "5.8.8-thr"
  - "5.8.8"
  - "5.8.5-thr"
  - "5.8.5"
  - "5.8.1-thr"
  - "5.8.1"
matrix:
  include:
    - perl: 5.14
      env: COVERAGE="coveralls codecov"
    - perl: 5.26
      env: COVERAGE="coveralls codecov"
  allow_failures:
    - perl: blead
    - perl: blead-thr
sudo: false
before_install:
  - eval $(curl -sS https://travis-perl.github.io/init) --auto

